on:
  push:
    tags:        
      - 'v*'
  workflow_dispatch:

name: Publish

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  publish:
    name: Publish rand_hash
    environment: crates.io
    runs-on: ubuntu-latest
    if: >-
      github.ref_type == 'tag' 
      && startsWith(github.ref_name, 'v')
    steps:
    - uses: actions/checkout@v3
    - run: cargo publish -p rand_hash
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
